project:
  artifactId: core-spring
  name: core-spring
  description: core-spring

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
  spring:
    profiles: ${spring.profiles.active:default}
