project:
  artifactId: boot-security
  name: boot-security
  description: boot-security

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
  spring:
    profiles: ${spring.profiles.active:default}
