---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: jdk8

inputs:
- name: core-spring-repo

run:
  user: root
  path: core-spring-repo/concourse/tasks/build-core-spring.sh